Update detekt.yml
.

diff --git a/.github/workflows/detekt.yml b/.github/workflows/detekt.yml
--- a/.github/workflows/detekt.yml
+++ b/.github/workflows/detekt.yml
@@ -51,33 +51,29 @@ jobs:
     - name: Get Detekt download URL
       id: detekt_info
       env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
-          query getReleaseAssetDownloadUrl($tagName: String!) {
-            repository(name: "detekt", owner: "detekt") {
-              release(tagName: $tagName) {
-                releaseAssets(name: "detekt", first: 1) {
-                  nodes {
-                    downloadUrl
-                  }
-                }
-                tagCommit {
-                  oid
-                }
+       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    run: |
+     gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
+      query getReleaseAssetDownloadUrl($tagName: String!) {
+        repository(name: "detekt", owner: "detekt") {
+          release(tagName: $tagName) {
+            releaseAssets(name: "detekt", first: 1) {
+              nodes {
+                downloadUrl
               }
             }
           }
-        ' 1> gh_response.json
+        }
+      }
+    ' 1> gh_response.json
 
-        DETEKT_RELEASE_SHA=$(jq --raw-output '.data.repository.release.releaseAssets.tagCommit.oid' gh_response.json)
-        if [ $DETEKT_RELEASE_SHA != "37f0a1d006977512f1f216506cd695039607c3e5" ]; then
-          echo "Release tag doesn't match expected commit SHA"
-          exit 1
-        fi
+    DETEKT_DOWNLOAD_URL=$(jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl' gh_response.json)
+    if [ -z "$DETEKT_DOWNLOAD_URL" ]; then
+      echo "Failed to retrieve Detekt download URL"
+      exit 1
+    fi
 
-        DETEKT_DOWNLOAD_URL=$(jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl' gh_response.json)
-        echo "download_url=$DETEKT_DOWNLOAD_URL" >> $GITHUB_OUTPUT
+    echo "download_url=$DETEKT_DOWNLOAD_URL" >> $GITHUB_OUTPUT
 
     # Sets up the detekt cli
     - name: Setup Detekt
